### ISSUE TITLE
Location variable in IL data

### ISSUE THREAD

**Issue by dr-mattross** [stanford-policylab/opp#62]
The documentation for the IL data states that:

_"For state patrol stops, there is mostly no information on the county of the stop. Instead, stops are mapped to districts (see the district column), which have a one-to-many relationship with counties."_

I dont believe that this is actually true. The variable titled `location' appears to be a zipcode which I have successfully linked to counties. I believe that the variable `beat' contains the districts discussed above.

**Comment by amyshoe** [comment]
Thank you -- we have updated the data readme to reflect this.

**Comment by dr-mattross** [comment]
Thanks. Also, is the data from 2004+ from IL not available because there is
something wrong with it or was it just not w/in the sample frame of the
most recent study. The documentation read like it was just outside the
sample frame. If so, would it be possible to get the extra years?

On Mon, Oct 7, 2019 at 2:02 PM Amy Shoemaker <notifications@github.com>
wrote:

> Closed #62
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stanford-2Dpolicylab_opp_issues_62&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=6IQlDs-NscdzMVia_44PSQ&m=2xRnPazitbjN3BZcy-0nVpcO4N2ioTCC1wfmC3bEHC0&s=C-iJOX6HyJhxd5g-mga7-XRD_xHIUqj_QdbenagB5QM&e=>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stanford-2Dpolicylab_opp_issues_62-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DANNJ7WQC4ZVCDEQ3HNPBIATQNN2RXA5CNFSM4I6HNPN2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUCAJQFY-23event-2D2692782103&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=6IQlDs-NscdzMVia_44PSQ&m=2xRnPazitbjN3BZcy-0nVpcO4N2ioTCC1wfmC3bEHC0&s=sz4tBWWdRjCzCc7jly5tzL8zdidcGF1ss9nv7AznFeU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANNJ7WTOV6VA75VQUHGCSTLQNN2RXANCNFSM4I6HNPNQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=6IQlDs-NscdzMVia_44PSQ&m=2xRnPazitbjN3BZcy-0nVpcO4N2ioTCC1wfmC3bEHC0&s=mZwwWdT0BT61Syy6lYqNxnVe8tMCniDZEW71_M-rGGo&e=>
> .
>


-- 

Regards,

Matthew B. Ross, Ph.D.
Research Assistant Professor
Wagner School of Public Service
Center for Urban Science + Progress
New York University

(m) 978.888.8517
(e) MBRoss@NYU.edu
www.MBRoss-Econ.com <http://www.mbross-econ.com/>
